identifier: k5f220bff4x8r4f6
allowErrorCollect: false
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: ngx-scully-blog
homeFolder: /home/nhaancs/workspace/ngx-scully-blog
distFolder: dist/ngx-scully-blog
outDir: /home/nhaancs/workspace/ngx-scully-blog/dist/static
handle404: ''
